# services/ocs-inventory/2.9/defaults/cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-config
data:
  values.yaml: |
    phpconfig:
      ocsinventory: |
        upload_max_filesize = 200M
        post_max_size = 201M
        max_execution_time = -1
        max_input_time = -1
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: 200M
        # ... các annotations khác